version: '3.9'
services:
  mysqldb:
    image: mysql:8.0.31
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
      - MYSQL_DATABASE=rabook
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  # webapi:
  #   build:
  #     context: ./webapi
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysqldb
  #   environment:
  #     - MYSQL_HOST=mysqldb
  #     - MYSQL_USERNAME=root
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_DATABASE=rabook
  #     - MYSQL_PORT=3306
  #   restart: always
  
  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=rabook
      - MYSQL_PORT=3306
    volumes:
      - ./webapi:/webapi
    command: ["mvn", "spring-boot:run", "-Dmaven.test.skip=true"]
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - './webapp:/app'
      - '/app/node_modules'
    ports:
      - 80:4200

      
volumes:
  db:
